### ISSUE TITLE
Move error

### ISSUE THREAD

**Issue by sebaemanuelgo** [lukemoore66/roc#1]
hi!, So far I had used this tool without problems, but I changed computers and it throws me the following error, I do not know why it happens, I am using Windows 10 oct update (I apologize if it is not understood I used a translator), thanks
[
![error](https://user-images.githubusercontent.com/62518824/101987872-57fd7280-3c75-11eb-8b59-97427c16b558.png)
](url)

**Comment by lukemoore66** [comment]
Hard to say, as I don't understand the language. It seems to be PowerShell not seeing the destination path as valid.
-Make sure your destination path has write permissions.
-Make sure all file paths do not have any weird characters. e.g. Left/Right Square Bracket ([,]) or Quotation marks of any kind ('`")

**Comment by gboquizosanchez** [comment]
I have the same issue. It seems there is a problem when all is encoded and Windows try to move because the item does not exist when it tries to move it...

**Comment by gboquizosanchez** [comment]
_Move-Item : No se puede mover el elemento porque no existe el elemento situado en_

Move-Item : The element can be moved because the element placed on "path here" doesn't exist...

**Comment by gboquizosanchez** [comment]
I have found issue.

![image](https://user-images.githubusercontent.com/20032391/146119371-cafd3393-d7a0-4661-9145-c8fd31581a79.png)

It seems Spanish chapters trait chapters with comma instead of dot for milliseconds... 

I'll open a PR asap.

**Comment by lukemoore66** [comment]
I see. Definitely fixable.  I wont be able to get onto this for a few weeks though, as I work in retail and I am amongst the Christmas rush right now. Thank you for reporting.

**Comment by lukemoore66** [comment]
Fixed by converting comma (,) to stop (.) when converting sexagesimal time strings. Implementing proper localization is not possible as the user may download different binaries for mkvtoolnix and ffmpeg. This fix should cover almost everything except some very specific edge cases.
