### ISSUE TITLE
Problem with the sample rate is different

### ISSUE THREAD

**Issue by gboquizosanchez** [lukemoore66/roc#2]
I have some problems related about audio sample rate.  Can you in certain way make all audios with same sample rate in script in order to avoid this error?

It is really annoying transform all chapter and when is finished it throws an error and you have to encode again... Or... when it fails the script doesn't delete encoded...

Thanks in advance!

**Comment by lukemoore66** [comment]
Can you show me a copy of the error output if possible? This script does resample everything to the same sample rate and bit depth. I have a suspicion it is not a bug with this program, but ffmpeg, which my script uses for resampling. It sometimes does this with the aformat filter. I may be able to work around it if this is the case.

**Comment by lukemoore66** [comment]
I have implemented an experimental fix. Please download the libroc.ps1 file in the Code tab [Here](https://github.com/lukemoore66/roc), and put it in the program's folder. Let me know how you go, as I do not have the time to test it for a couple of days.

**Comment by gboquizosanchez** [comment]
I'll put you some screenshots for the issue asap. And I'll test your experimental fix too.

Thanks!

**Comment by gboquizosanchez** [comment]
Image with "The sample rate of the two audio tracks is different: 48000 and 44100"

![image](https://user-images.githubusercontent.com/20032391/152621103-a9ebe06a-3a64-44f3-a4a6-b702641ffaba.png)

In order to debug this... I had to add some changes in the code. 

Comment Cleanup-Files function on roc.ps1. 

And, to add Write-Host $strMkvMerge in Merge-Segments function 😐. 

I think this is caused because try catch is not working with .\bin\mkvmerge.exe command...

![image](https://user-images.githubusercontent.com/20032391/152621724-acc72733-d3e5-48d9-b38e-1aa7e5d3d43c.png)

This happen when an error is thrown~. 

And the last one thing! Great job with the experimental fix, it's working perfectly! Thanks 😉

**Comment by lukemoore66** [comment]
Thank you for your debugging efforts, it's would seem I was on the money. Good to know the sample rate is now converting correctly, I was using an older method, but the newer method works correctly now. As for PowerShell not catching the error, it would seem mkvmerge does not class appending errors as terminating errors, so I will change the logic to throw an error if the output is anything other than successful. I have raised a new issue for this bug. Thank you very much for your input.

**Comment by gboquizosanchez** [comment]
Thank you for all!
